## Numpy
- Numpy is a special python library that deals with numbers
* Arrays are special data structures that numpy offers 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# creating N-dim arrays 
arrays =  np.arange(8)
arrays

array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
print(type(arrays))

<class 'numpy.ndarray'>


In [4]:
# If we don't want 0 in our array
arr =  np.arange(1,8)
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# If we want to step 2 values ( we want odd numbers)
odd = np.arange(1,8,2)
odd

array([1, 3, 5, 7])

In [6]:
# To generate float values 
floatt = np.arange(1,8,0.5)
floatt

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5])

In [7]:
# to deal with -ve as well as float values
neg_flo = np.arange(-1,8,0.25)
neg_flo

array([-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,
        1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,
        3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,  5.5 ,
        5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,  7.75])

In [8]:
# to generate arrays from list 
lis = np.array([1,2,3])
print(type(lis[0])) # to know storage of variable 

<class 'numpy.int32'>


we need only 2 bit to store 3 numbers. For this reason specify dtype = 8 ( or any number )

In [9]:
# to reduce storage of variabl 
lis = np.array([1,2,3] , dtype = np.int8)
print(type(lis[0]))

<class 'numpy.int8'>


In [10]:
#2D Arrays
arr = np.array([[1,2,3],[4,5,6]] , dtype = np.int8)
arr

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [11]:
# to create a 2D array from arange function 
arr = np.array((np.arange(0,8,2) , np.arange(1,8,2)))
arr

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [12]:
print("1D shape:" , lis.shape) 
print("2D shape:" , arr.shape)

1D shape: (3,)
2D shape: (2, 4)


In [13]:
# to change the sahpe of an array
d =  arr.reshape((4,2))
d

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [14]:
# 3D Array
ddd = arr.reshape((2,2,2))
ddd

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [15]:
# to create an empty array
emp = np.zeros((2,2))
emp

array([[0., 0.],
       [0., 0.]])

In [16]:
# ones 
ones = np.ones((2,2))
ones 

array([[1., 1.],
       [1., 1.]])

In [17]:
# for this code it will return zeros 
empty = np.empty((2,2))
empty 

array([[1., 1.],
       [1., 1.]])

In [18]:
# but for this it will return random values
emo_val = np.empty((2,2,2))
emo_val

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 6.32404027e-321],
        [1.05699242e-307, 3.11523242e-307]]])

In [19]:
# to create diagonal array
eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# 1 diag above
dia_ab = np.eye(3 , k = 1)
dia_ab

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [24]:
# 1 diag below 
diao_bel = np.eye(3 , k = -1)
dia_ab

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [28]:
# to manipulate this array
eye[eye == 0] = 2
print("all 0's are converted to 2:" , eye)

all 0's are converted to 2: [[1. 2. 2.]
 [2. 1. 2.]
 [2. 2. 1.]]


In [29]:
eye[eye < 2] = 9
print(eye, "all the values are converted to 9 which are less than 2")

[[9. 2. 2.]
 [2. 9. 2.]
 [2. 2. 9.]] all the values are converted to 9 which are less than 2


In [30]:
# 1st row to fill with 3
eye[0] = 3
print(eye, "1st row values will be changed to 3")

[[3. 3. 3.]
 [2. 9. 2.]
 [2. 2. 9.]] 1st row values will be changed to 3


In [39]:
# 1st 2 rows to fill 3
eye[:2]=1
print(eye)

[[1. 1. 1.]
 [1. 1. 1.]
 [5. 5. 4.]]


In [40]:
# last 2 rows to fill as 3
eye[1:]=6
print(eye)

[[1. 1. 1.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [41]:
# 1st col = 4
eye[:,0]=4
print(eye)

[[4. 1. 1.]
 [4. 6. 6.]
 [4. 6. 6.]]


In [42]:
## to select from end lst column 
eye[:,-1]=7
eye

array([[4., 1., 7.],
       [4., 6., 7.],
       [4., 6., 7.]])

In [43]:
# to cahnge last 2 rows = 4 and first 2 cols =  5
eye[1:,:2] = 5
eye

array([[4., 1., 7.],
       [5., 5., 7.],
       [5., 5., 7.]])

## Numpy practice 

In [ ]:
import numpy as np

In [ ]:
# how to load diff types of arrays 
# 1st method 
x = np.array([58,55,50.6])

In [ ]:
# 2nd method
x1 = np.linspace(0,10,5)
x1

In [ ]:
# 3rd method 
x2 = np.arange(1,8,2)
x2

In [ ]:
# basic plot 
x = np.linspace(0,20,10)
y = x**2

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x,y,'r--')
plt.xlabel('X',fontsize = 15)
plt.ylabel('Y', fontsize = 15)

In [ ]:
plt.plot(x,y,'red')

In [ ]:
a = np.array([3,5,7,9])

In [ ]:
# gives 
b = np.linspace(0,20,10)
b

In [ ]:
c = np.arange(1,20,2)
c

In [ ]:
zeros  = np.zeros(10)
zeros

In [ ]:
ones = np.ones(10)
ones

In [ ]:
# gives random numbers b/w (0 to 10)
random_num = np.random.random(10)
random_num

In [ ]:
# gives random numbes based on gausion distribution ( where mean =0 and std =1 )
randn_num = np.random.randn(10)
randn_num

- List & Arrays are similar but in Arrays we can do elemnt wise Operations where as in List we can't

In [ ]:
# Arrays Operations 
a

In [ ]:
2/a

In [ ]:
a+2

In [ ]:
1/a+a/9+a

In [ ]:
x = np.linspace(0,1,100)
y = x**2

In [ ]:
plt.plot(x,y,'r--')
plt.xlabel('X', fontsize = 20)
plt.ylabel('Y',fontsize=20)

In [ ]:
# we can also chain functions together (x^2*sinx/e^-x) 
def f(x):
    return x**2*np.sin(x)/np.exp(-x)
x = np.linspace(0,10,100)
y = f(x)
plt.plot(x,y)

In [ ]:
# Arrays Indexing /Slicing 
a1 = np.array([2,58,55,66,54])

In [ ]:
a1[2:]

In [ ]:
a1[:-2]

In [ ]:
a1[1:-2]

In [ ]:
# Boolean Indexing 
a1>3

In [ ]:
a1

In [ ]:
# Give numbers which are greater than 3
a1[a1>3]

In [ ]:
# Eample ( this is like give me string I will give you 1st elemtnt of that stirng)
f = lambda s:s[0]
f('animal')

In [ ]:
# Suppose we want only values which start with 'J'
names = np.array(['James','John Cena','HHH','Conor','Khabib'])

In [ ]:
# For this type of problem we can use for loop or use np.vectorize 
fst_letter_J = np.vectorize(lambda s:s[0])(names)=='J'
fst_letter_J

In [ ]:
names[fst_letter_J]

In [ ]:
# example To caheck wheter a1 is divisble by 4
a1 = np.array([2,4,6,8,10])

In [ ]:
a1%4

In [ ]:
a1%4==0

In [ ]:
a1[a1%4==0]

In [ ]:
## Calculus /Statistical functions 
a = 2*np.random.randn(1000)+10
a

- randn gives 1000 values with mean = 0 and std = 1
- 10 will shift the mean and multiplying with 2 will expand std

In [ ]:
# finding mean 
np.mean(a)

In [ ]:
# finding STD
np.std(a)

In [ ]:
# to find out how many % of numbers are less than 80
np.percentile(a,80)

- this means 11.%78 values are less than 80

## Integrals and Derivatives 

In [ ]:
# Example
np.cumsum(np.array([2,4,5]))

In [ ]:
x = np.linspace(1,10,100)
y = 1/x**2*np.sin(x)

In [ ]:
plt.plot(x)

In [ ]:
# find derivative
dydx = np.gradient(y,x)

In [ ]:
# find integrals
y_int = np.cumsum(y)*(x[1]-x[0])


In [ ]:
plt.plot(x,y,'r')
plt.plot(x,dydx,'g')
plt.plot(x,y_int,'b')

# Exapmle Problemms 
- Let $y = e^{-x/10}sin(x)$ consider 10000$x$ intervals in the range [0,10]
1. Plot $y$ vd $x$ in range [0,10] 
2. Compute the mean and std of $y$ for $x$ values in [4,7]
3. For $x$ in range [4,7] find the value of $y_m$ such that 80% of y values are less thab $y_m$
4. Plot $dydx$ vs $x$
5. Find locations where $dydx$ = 0 $(root findig)$

In [ ]:
#1 
N = 10000
x = np.linspace(0,10,N+1)
y = np.exp(-x/10)*np.sin(x)
plt.plot(x,y,'black')
plt.xlabel('X',fontsize = 15)
plt.ylabel('Y',fontsize = 15)

In [ ]:
#2 
x >=4

In [ ]:
x<=7

In [ ]:
(x>=4)*(x<=7)

In [ ]:
y[(x>=4)*(x<=7)]

In [ ]:
#2
# mean
np.mean(y[(x>=4)*(x<=7)])

In [ ]:
# std
np.std(y[(x>=4)*(x<=7)])

In [ ]:
#3 (use percentile for this)
np.percentile(y[(x>=4)*(x<=7)],80)

In [ ]:
#4 
dydx = np.gradient(y,x)
plt.plot(x,dydx,'b')
plt.xlabel('X')
plt.ylabel('dydx')

In [ ]:
#5.(root finding) dydx =0
dydx = np.gradient(y,x)
dydx

In [ ]:
dydx[1:]

In [ ]:
dydx[:-1]

In [ ]:
dydx[1:]*dydx[:-1]<0

In [ ]:
x[1:][dydx[1:]*dydx[:-1]<0]

This (rootfinding ) is like we have graph and there is data points at one point when we go below from above and above from below we get at a point where we get origin 

# Question 
- Sum together every number from 0 to 10000 except fot those that can not be divided by 4 or 7. Do this in one line of code 

In [ ]:
np.arange(0,10001,1)

In [ ]:
# example (we are checking all the numbers that can  be divided by 4)
np.array([4,8,10])%4

In [ ]:
np.arange(0,10001,1)%4

In [ ]:
# numbers not divided by four 
np.arange(0,10001,1)%4!=0

In [ ]:
(np.arange(0,10001,1)%4!=0)*(np.arange(0,10001,1)%7!=0)

In [ ]:
num = np.arange(0,10001,1)

In [ ]:
sum(num[(num%4!=0)*(num%7!=0)])

# Question 3 (Polar Coordinates)
- Consider the flower petal $r(\theta) = 1+3/4 sin(3\theta)$ for  $0 <= \theta <= 2\pi $
1. Make a plot of the flower ( find x and Y points)
2. Compute the area using the calculus formula $A = \int_{0}^{2\pi}  \frac{1}{2}r^2{d\theta}$
3. Compute the arclength using the calculus formula $L = \int_{0}^{2\pi} \sqrt{r^2 + (\frac{dr}{d\theta})^2 d\theta}$

In [ ]:
#1
theta = np.linspace(0,2*np.pi,1000)
r = 1+3/4*np.sin(3*theta)

- Magnetic field of any current loop is $r(\theta) = 1+3/4 sin(3\theta)$
- We know that $x = rcos(\theta)$ and $y = rsin(\theta)$

In [ ]:
x = r*np.cos(theta)
y = r*np.sin(theta)

In [ ]:
plt.plot(x,y,'y')

In [ ]:
#2.
A = 1/2*sum(r**2)*(theta[1]-theta[0])
A

In [ ]:
#3.
L = sum(np.sqrt(r**2 + np.gradient(r,theta)**2))*(theta[1] - theta[0])
L

We used sum for integral and gradient for differentiation

# Question 
- The power emitted by a blackbody is $P = A \sigma \epsilon T^4$ . After measuring the temperature of a star you find that $T(t) = T_o \frac{1}{1+e^{-kt}}$ . Plot the total  energy emitted by the star as a function of time using a fact that $E(t) = \int_{t^{1} = 0}^{t^{1}=t} P(t^{1}) dt^{1}$

- $p/(A\sigma\epsilon T_o) = (\frac{1}{1+e^{-kt}})^4$

In [ ]:
kt = np.linspace(0,3,100)
p = (1/(1+np.exp(-kt)))**4

In [ ]:
plt.plot(kt,p)

In [ ]:
E = np.cumsum(p)*(kt[1]-kt[0])


In [ ]:
plt.plot(kt,p,'black')
plt.plot(kt,E,'r')
plt.xlabel('$kt$', fontsize = 20)
plt.ylabel('$p/(A\sigma\epsilon)    (E(kt))$',fontsize = 20)

# Multidimensional Arrays

In [ ]:
# crating multi dim Arrays
a = np.array([[2,1,5,4],[21,22,5,5],[4,5,9,8]])
a

In [ ]:
# To convert any dim Array into one dim (use np.ravel)
a.ravel()

In [ ]:
a>5

In [ ]:
a1 = np.random.randn(3,3,3),
a1

Gives 3 sim arrays and 3 diff 3 dim arrays

In [ ]:
a = np.random.randn(3,3)
a

In [ ]:
a[a>1]

In [ ]:
#Element indexing
a[0]

In [ ]:
# gives only last row 
a[2]

In [ ]:
# Gives all the rows and 1st col
a[:,0]

In [ ]:
a[1:,2]

# Dealing with 2D functions 
- meshgrid is used to convert 2 diff arrays of diff or same lenght into 2D Array

In [ ]:
x = np.linspace(0,10,1000)
y = np.linspace(0,10,1000)

In [ ]:
xv,yv = np.meshgrid(x,y)
zv = xv**2+yv**2

In [ ]:
# Contour plot
plt.contour(xv,yv,zv,levels = 30)
plt.colorbar()

In [ ]:
# Basic Linear Algebra Matrix Operations
A = np.array([[3,2,1],[5,-5,4],[6,0,1]])
b1 = np.array([1,2,3])
b2 = np.array([-1,2,-5])

A is matrix and b1 and b2 is vectors 

In [ ]:
# matrix operations (@ means into (operation))
A@b1

In [ ]:
# Transpose
A.T

In [ ]:
# Finding dot product 
np.dot(b1,b2)

In [ ]:
# finding cross product
np.cross(b1,b2)

# System Of Equations
- $3x+2y+z = 4$
- $5x-5y+4 = 3$
- $6x+z = 0$

In [ ]:
A = np.array([[3,2,1],[5,-5,4],[6,0,1]])
c = np.array([4,3,0])

In [ ]:
# To solve the equation
np.linalg.solve(A,c)

In [ ]:
# Finding eigen values and eigen vector
w,v = np.linalg.eig(A)

W = eigen values and v = eigen vectors

In [ ]:
w,v

In [ ]:
v1 = v[:,0]
v1

In [ ]:
A@v1

In [ ]:
w[0]*v1

# Example
Let $f(x,y) = e^{-(x^2+y^2)}sin(x)$ for $-2\le y \ge 2$
1. Make a Contour plot of $f$
2. Find the  volume $|f(x,y)|$ on the specified $x$&$y$ range 
3. Find the value $|f(x,y)|$ only in the region where $\sqrt{x^2+y^2} >0.5$ 

In [ ]:
#1
x = np.linspace(-2,2,1000)
y = np.linspace(-2,2,1000)
xv,yv = np.meshgrid(x,y)

In [ ]:
f = np.exp(-(xv**2+yv**2))*np.sin(xv)

In [ ]:
plt.contourf(xv,yv,levels=100)
plt.colorbar()

In [ ]:
#2 
# f is 2D array (so convert it into a 1D array)
np.abs(f.ravel())

np.diff(x)[0] (this is dx) np.diff(y)[0] (this is dy)

In [ ]:
np.abs(f.ravel()).sum()*np.diff(x)[0]*np.diff(y)[0]

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#3. (this ia a bit difficult)
xv**+yv**2 >0.5**2

In [ ]:
np.abs(f[xv**+yv**2 >0.5**2].ravel()).sum()*np.diff(x)[0]*np.diff(y)[0]

# Question 
## After axamining a circuit full of resistors you find the voltage at 4 specified points is given by 
- $3V_1 + 2V_2 + 3V_3 +10V_)4 = 4$
- $ 2V_1 - 2V_2 + 5V_3 + 8V_4 = 3$
- $3V_1 + 4V_2 -3V_3 - 7V_4 = 2$
- find all the voltages

In [ ]:
A = np.array([[3,2,3,10],[2,-2,5,8],[3,3,4,9],[3,4,-3,-7]])
c = np.array([4,1,3,2])

In [ ]:
np.linalg.solve(A,c)

# Question 
- An electric field is given by $\vec{E}(Z,t) = E_ocos(Z-t)\hat{x}+2E_o cos(Z-t+\pi/2)\hat{y}$
1. Find the magnetic field for all $Z$ $\epsilon$ $[0,4\pi]$ and $t$ $\epsilon$ $[0,10]$ using $\vec{B}(Z,t)$ = $\hat{Z}\times\hat{E}(Z,t)$
2. Compute the poynting vector $\vec{S}$ = $\vec{E}\times\vec{B}$ for all $Z$ and $t$

In [ ]:
#1.
z = np.linspace(0,4*np.pi,100)
t = np.linspace(0,10,100)
tv,zv = np.meshgrid(t,z)

In [ ]:
Ex = np.cos(zv-tv)
Ey = 2*np.cos(zv-tv+np.pi/2)
Ez = 0*tv

In [ ]:
Ex

In [ ]:
plt.plot(t,Ex[0])

$E_x$ as functttion of $t$ at $z=0$

In [ ]:
plt.plot(t,Ex[:,0])

$E_x$ as functttion of $z$ at $t=0$

In [ ]:
E = np.array([Ex,Ey,Ez])


In [ ]:
E = np.swapaxes(E,0,-1)
E

Inorder to swap the axes and name (x,y,z) into one single vector insted of x diff, y diff and z diff

In [ ]:
B = np.cross(np.array([0,0,1]),E)


In [ ]:
B = np.swapaxes(B,0,-1)

Inorder to make it original 

In [ ]:
Bx,By,Bz = B

In [ ]:
plt.plot(t,Ey[0])
plt.plot(t,Bx[0])

In [ ]:
#3.
B = np.swapaxes(B,0,-1) # because it is not in the right form 


E was in the correct form (vector,vector,vector(3 sep vec)) whereas B was not in the correct form it is in 2D array form thats why we swapd axes of B

In [ ]:
S = np.cross(E,B)

In [ ]:
S = np.swapaxes(S,0,-1)


In [ ]:
Sx,Sy,Sz = S

In [ ]:
Sz

# Question 4 
- Find the solution to $(\frac{d^2}{dx^2}+(10x)^2)f$ = $\lambda$$f$ with boundary condition $f(0) = f(1) = 0$ 
- use the eigenvalue method and the fact that $\frac{d^2f}{dx^2}\approx \frac{f_{i+1}+f_{i-1}-2f_i}{\Delta x^2}$ where $f_i = f(i\Delta x)$ and $i$ is an integer ( it is int he form $(\frac{d^2}{dx^2}+h(x))f(x)$ = $\lambda$$f$)

In [ ]:
N = 1000
x = np.linspace(0,1,N+1)
dx = x[1]-x[0]
moving_diag = -2*np.ones(N-1)
off_diag = np.ones(N-2)

In [ ]:
deriv_matr = np.diag(moving_diag)
deriv_matr

In [ ]:
np.diag(moving_diag)

In [ ]:
np.diag(off_diag,1)

In [ ]:
deriv_matr = (np.diag(moving_diag) + np.diag(off_diag,-1) + np.diag(off_diag,1))/dx**2
deriv_matr

In [ ]:
x2_matrix  = np.diag((10*x[1:-1])**2)

In [ ]:
LHS_matrix = deriv_matr + x2_matrix

In [ ]:
w,v = np.linalg.eigh(LHS_matrix)

In [ ]:
w[-1]

smallest of eigen values 

In [ ]:
# plot all the eigen vectors 
plt.plot(v[:,-1])
plt.plot(v[:-2])
plt.plot(v[:,-3])
plt.plot(v[:,-4])
plt.show()

In [ ]:
# to convert dtyoe to string 
# name.astyoe(str)

In [ ]:
# To convert dtype to float 
# height.astype(float)